using Kentico.Xperience.Admin.Base;
using Kentico.Xperience.Admin.Base.FormAnnotations;

using XperienceCommunity.SqlBrowser.Enum;

namespace XperienceCommunity.SqlBrowser.Admin.Models;

/// <summary>
/// Represents the configuration of the SQL result export process, presented to the user in a confirmation dialog.
/// </summary>
[CommandConfirmationModel]
public class ExportConfirmationDialogModel
{
    /// <summary>
    /// The desired export file type, as string representations of <see cref="SqlBrowserExportType"/>.
    /// </summary>
    [DropDownComponent(
        Label = "Type",
        Options = "CSV\r\nExcel\r\nJSON")]
    [RequiredValidationRule]
    public string? ExportType { get; set; } = "CSV";


    /// <summary>
    /// The desired export file name. If <c>null</c> or empty, the name should be autogenerated.
    /// </summary>
    [TextInputComponent(
        Label = "File name (without extension)",
        WatermarkText = "Leave empty to autogenerate")]
    public string? FileName { get; set; }
}
